databases:
  - name: beautybookingdb
    plan: free
    databaseName: beautybooking
    user: beautybooking

services:
  - type: web
    plan: free
    name: beautybooking
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: beautybookingdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4